FROM registry.cn-hangzhou.aliyuncs.com/zhfang/jdk:1.8.0_131

MAINTAINER zhfang

ENV CATALINA_HOME /opt/tomcat
ENV PATH $PATH:$CATALINA_HOME/bin:$CATALINA_HOME/scripts


# Install Tomcat
RUN wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.38/bin/apache-tomcat-8.0.38.tar.gz && \
        tar -xvf apache-tomcat-8.0.38.tar.gz && \
        rm apache-tomcat*.tar.gz && \
        mv apache-tomcat* ${CATALINA_HOME}

COPY jmx_prometheus_javaagent-0.12.0.jar /opt/tomcat
COPY config.yml /opt/tomcat 

CMD catalina.sh run 
